server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_db
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update

keycloak:
  realm: myrealm
  auth-server-url: http://localhost:8080/auth
  resource: holiday-tracker-client
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: http://localhost:8080/realms/myrealm

jwt:
  issuer:
    auth : http://localhost:8080/realms/myrealm
    admin: http://localhost:8080/realms/master

