name: Holiday tracker CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '19'
          cache: 'maven'

      - name: Build Shared Libraries
        run: mvn clean install -DskipTests -pl shared-libraries -am

      - name: Build & Test UserService
        run: mvn clean verify -pl user-service -am

      - name: Build & Test AutoService
        run: mvn clean verify -pl auto-service -am

      - name: Build & Test HolidayService
        run: mvn clean verify -pl holiday-service -am

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Images
        run: |
          docker build -t auth-service:latest backend/auth-service
          docker build -t holiday-service:latest backend/holiday-service
          docker build -t ser-service:latest backend/user-service
          docker build -t frontend:latest frontend

      - name: Push Docker Images
        run: |
          docker push auth-service:latest
          docker push holiday-service:latest
          docker push ser-service:latest
          docker push frontend:latest

#  deploy:
#    runs-on: ubuntu-latest
#    needs: docker
#    steps:
#      - name: Setup Kubectl
#        run: |
#          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
#          chmod +x kubectl
#          sudo mv kubectl /usr/local/bin/
#      - name: Deploy to Kubernetes
#        run: kubectl apply -f backend/infra/k8s/
