apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: your-docker-registry/auth-service:latest
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: holiday-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: holiday-service
  template:
    metadata:
      labels:
        app: holiday-service
    spec:
      containers:
      - name: holiday-service
        image: your-docker-registry/holiday-service:latest
        ports:
        - containerPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: your-docker-registry/user-service:latest
        ports:
        - containerPort: 8082